<?php

/**
 * Implements hook_theme().
 */
function metatag_link_preview_theme($existing, $type, $theme, $path) {
  return [
    'preview_container' => [
      'variables' => [
        'meta_tag_values' => NULL,
        'preview_cards' => NULL,
      ],
    ],
    'search_engine_card' => [
      'variables' => [
        'title' => NULL,
        'link' => NULL,
        'description' => NULL,
      ]
    ]
  ];
}
